/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.BrandingRequestCompoundV2;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Request for PUT /2/object/branding/{pkiBrandingID}
 **/
@ApiModel(description = "Request for PUT /2/object/branding/{pkiBrandingID}")
public class BrandingEditObjectV2Request {
  
  @SerializedName("objBranding")
  private BrandingRequestCompoundV2 objBranding = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public BrandingRequestCompoundV2 getObjBranding() {
    return objBranding;
  }
  public void setObjBranding(BrandingRequestCompoundV2 objBranding) {
    this.objBranding = objBranding;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BrandingEditObjectV2Request brandingEditObjectV2Request = (BrandingEditObjectV2Request) o;
    return (this.objBranding == null ? brandingEditObjectV2Request.objBranding == null : this.objBranding.equals(brandingEditObjectV2Request.objBranding));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.objBranding == null ? 0: this.objBranding.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BrandingEditObjectV2Request {\n");
    
    sb.append("  objBranding: ").append(objBranding).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
