/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.CreditcardmerchantResponseCompound;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Payload for GET /2/object/creditcardmerchant/{pkiCreditcardmerchantID}
 **/
@ApiModel(description = "Payload for GET /2/object/creditcardmerchant/{pkiCreditcardmerchantID}")
public class CreditcardmerchantGetObjectV2ResponseMPayload {
  
  @SerializedName("objCreditcardmerchant")
  private CreditcardmerchantResponseCompound objCreditcardmerchant = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public CreditcardmerchantResponseCompound getObjCreditcardmerchant() {
    return objCreditcardmerchant;
  }
  public void setObjCreditcardmerchant(CreditcardmerchantResponseCompound objCreditcardmerchant) {
    this.objCreditcardmerchant = objCreditcardmerchant;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreditcardmerchantGetObjectV2ResponseMPayload creditcardmerchantGetObjectV2ResponseMPayload = (CreditcardmerchantGetObjectV2ResponseMPayload) o;
    return (this.objCreditcardmerchant == null ? creditcardmerchantGetObjectV2ResponseMPayload.objCreditcardmerchant == null : this.objCreditcardmerchant.equals(creditcardmerchantGetObjectV2ResponseMPayload.objCreditcardmerchant));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.objCreditcardmerchant == null ? 0: this.objCreditcardmerchant.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreditcardmerchantGetObjectV2ResponseMPayload {\n");
    
    sb.append("  objCreditcardmerchant: ").append(objCreditcardmerchant).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
