/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.3.2
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.CustomEzmaxcustomerResponse;
import org.openapitools.client.model.EmailResponseCompound;
import org.openapitools.client.model.PhoneResponseCompound;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * A Ezmaxcustomeruser Object
 **/
@ApiModel(description = "A Ezmaxcustomeruser Object")
public class CustomEzmaxcustomeruserResponse {
  
  @SerializedName("objEzmaxcustomer")
  private CustomEzmaxcustomerResponse objEzmaxcustomer = null;
  @SerializedName("fkiContacttitleID")
  private Integer fkiContacttitleID = null;
  @SerializedName("fkiLanguageID")
  private Integer fkiLanguageID = null;
  @SerializedName("objEmail")
  private EmailResponseCompound objEmail = null;
  @SerializedName("objPhone")
  private PhoneResponseCompound objPhone = null;
  @SerializedName("sEzmaxcustomeruserFirstname")
  private String sEzmaxcustomeruserFirstname = null;
  @SerializedName("sEzmaxcustomeruserLastname")
  private String sEzmaxcustomeruserLastname = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public CustomEzmaxcustomerResponse getObjEzmaxcustomer() {
    return objEzmaxcustomer;
  }
  public void setObjEzmaxcustomer(CustomEzmaxcustomerResponse objEzmaxcustomer) {
    this.objEzmaxcustomer = objEzmaxcustomer;
  }

  /**
   * The unique ID of the Contacttitle.  Valid values:  |Value|Description| |-|-| |1|Ms.| |2|Mr.| |4|(Blank)| |5|Me (For Notaries)|
   * minimum: 0
   **/
  @ApiModelProperty(required = true, value = "The unique ID of the Contacttitle.  Valid values:  |Value|Description| |-|-| |1|Ms.| |2|Mr.| |4|(Blank)| |5|Me (For Notaries)|")
  public Integer getFkiContacttitleID() {
    return fkiContacttitleID;
  }
  public void setFkiContacttitleID(Integer fkiContacttitleID) {
    this.fkiContacttitleID = fkiContacttitleID;
  }

  /**
   * The unique ID of the Language.  Valid values:  |Value|Description| |-|-| |1|French| |2|English|
   * minimum: 1
   * maximum: 2
   **/
  @ApiModelProperty(required = true, value = "The unique ID of the Language.  Valid values:  |Value|Description| |-|-| |1|French| |2|English|")
  public Integer getFkiLanguageID() {
    return fkiLanguageID;
  }
  public void setFkiLanguageID(Integer fkiLanguageID) {
    this.fkiLanguageID = fkiLanguageID;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public EmailResponseCompound getObjEmail() {
    return objEmail;
  }
  public void setObjEmail(EmailResponseCompound objEmail) {
    this.objEmail = objEmail;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public PhoneResponseCompound getObjPhone() {
    return objPhone;
  }
  public void setObjPhone(PhoneResponseCompound objPhone) {
    this.objPhone = objPhone;
  }

  /**
   * The First name of the Ezmaxcustomeruser
   **/
  @ApiModelProperty(required = true, value = "The First name of the Ezmaxcustomeruser")
  public String getSEzmaxcustomeruserFirstname() {
    return sEzmaxcustomeruserFirstname;
  }
  public void setSEzmaxcustomeruserFirstname(String sEzmaxcustomeruserFirstname) {
    this.sEzmaxcustomeruserFirstname = sEzmaxcustomeruserFirstname;
  }

  /**
   * The First name of the Ezmaxcustomeruser
   **/
  @ApiModelProperty(required = true, value = "The First name of the Ezmaxcustomeruser")
  public String getSEzmaxcustomeruserLastname() {
    return sEzmaxcustomeruserLastname;
  }
  public void setSEzmaxcustomeruserLastname(String sEzmaxcustomeruserLastname) {
    this.sEzmaxcustomeruserLastname = sEzmaxcustomeruserLastname;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomEzmaxcustomeruserResponse customEzmaxcustomeruserResponse = (CustomEzmaxcustomeruserResponse) o;
    return (this.objEzmaxcustomer == null ? customEzmaxcustomeruserResponse.objEzmaxcustomer == null : this.objEzmaxcustomer.equals(customEzmaxcustomeruserResponse.objEzmaxcustomer)) &&
        (this.fkiContacttitleID == null ? customEzmaxcustomeruserResponse.fkiContacttitleID == null : this.fkiContacttitleID.equals(customEzmaxcustomeruserResponse.fkiContacttitleID)) &&
        (this.fkiLanguageID == null ? customEzmaxcustomeruserResponse.fkiLanguageID == null : this.fkiLanguageID.equals(customEzmaxcustomeruserResponse.fkiLanguageID)) &&
        (this.objEmail == null ? customEzmaxcustomeruserResponse.objEmail == null : this.objEmail.equals(customEzmaxcustomeruserResponse.objEmail)) &&
        (this.objPhone == null ? customEzmaxcustomeruserResponse.objPhone == null : this.objPhone.equals(customEzmaxcustomeruserResponse.objPhone)) &&
        (this.sEzmaxcustomeruserFirstname == null ? customEzmaxcustomeruserResponse.sEzmaxcustomeruserFirstname == null : this.sEzmaxcustomeruserFirstname.equals(customEzmaxcustomeruserResponse.sEzmaxcustomeruserFirstname)) &&
        (this.sEzmaxcustomeruserLastname == null ? customEzmaxcustomeruserResponse.sEzmaxcustomeruserLastname == null : this.sEzmaxcustomeruserLastname.equals(customEzmaxcustomeruserResponse.sEzmaxcustomeruserLastname));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.objEzmaxcustomer == null ? 0: this.objEzmaxcustomer.hashCode());
    result = 31 * result + (this.fkiContacttitleID == null ? 0: this.fkiContacttitleID.hashCode());
    result = 31 * result + (this.fkiLanguageID == null ? 0: this.fkiLanguageID.hashCode());
    result = 31 * result + (this.objEmail == null ? 0: this.objEmail.hashCode());
    result = 31 * result + (this.objPhone == null ? 0: this.objPhone.hashCode());
    result = 31 * result + (this.sEzmaxcustomeruserFirstname == null ? 0: this.sEzmaxcustomeruserFirstname.hashCode());
    result = 31 * result + (this.sEzmaxcustomeruserLastname == null ? 0: this.sEzmaxcustomeruserLastname.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomEzmaxcustomeruserResponse {\n");
    
    sb.append("  objEzmaxcustomer: ").append(objEzmaxcustomer).append("\n");
    sb.append("  fkiContacttitleID: ").append(fkiContacttitleID).append("\n");
    sb.append("  fkiLanguageID: ").append(fkiLanguageID).append("\n");
    sb.append("  objEmail: ").append(objEmail).append("\n");
    sb.append("  objPhone: ").append(objPhone).append("\n");
    sb.append("  sEzmaxcustomeruserFirstname: ").append(sEzmaxcustomeruserFirstname).append("\n");
    sb.append("  sEzmaxcustomeruserLastname: ").append(sEzmaxcustomeruserLastname).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
