/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * A Customer AutocompleteElement Response
 **/
@ApiModel(description = "A Customer AutocompleteElement Response")
public class CustomerAutocompleteElementResponse {
  
  @SerializedName("pkiCustomerID")
  private Integer pkiCustomerID = null;
  @SerializedName("fkiDepartmentID")
  private Integer fkiDepartmentID = null;
  @SerializedName("sCustomerName")
  private String sCustomerName = null;
  @SerializedName("sCustomerCode")
  private String sCustomerCode = null;
  @SerializedName("bCustomerIsactive")
  private Boolean bCustomerIsactive = null;

  /**
   * The unique ID of the Customer.
   * minimum: 0
   **/
  @ApiModelProperty(required = true, value = "The unique ID of the Customer.")
  public Integer getPkiCustomerID() {
    return pkiCustomerID;
  }
  public void setPkiCustomerID(Integer pkiCustomerID) {
    this.pkiCustomerID = pkiCustomerID;
  }

  /**
   * The unique ID of the Department
   * minimum: 0
   **/
  @ApiModelProperty(required = true, value = "The unique ID of the Department")
  public Integer getFkiDepartmentID() {
    return fkiDepartmentID;
  }
  public void setFkiDepartmentID(Integer fkiDepartmentID) {
    this.fkiDepartmentID = fkiDepartmentID;
  }

  /**
   * The name of the Customer
   **/
  @ApiModelProperty(required = true, value = "The name of the Customer")
  public String getSCustomerName() {
    return sCustomerName;
  }
  public void setSCustomerName(String sCustomerName) {
    this.sCustomerName = sCustomerName;
  }

  /**
   * The code of the Customer
   **/
  @ApiModelProperty(required = true, value = "The code of the Customer")
  public String getSCustomerCode() {
    return sCustomerCode;
  }
  public void setSCustomerCode(String sCustomerCode) {
    this.sCustomerCode = sCustomerCode;
  }

  /**
   * Whether the customer is active or not
   **/
  @ApiModelProperty(required = true, value = "Whether the customer is active or not")
  public Boolean getBCustomerIsactive() {
    return bCustomerIsactive;
  }
  public void setBCustomerIsactive(Boolean bCustomerIsactive) {
    this.bCustomerIsactive = bCustomerIsactive;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerAutocompleteElementResponse customerAutocompleteElementResponse = (CustomerAutocompleteElementResponse) o;
    return (this.pkiCustomerID == null ? customerAutocompleteElementResponse.pkiCustomerID == null : this.pkiCustomerID.equals(customerAutocompleteElementResponse.pkiCustomerID)) &&
        (this.fkiDepartmentID == null ? customerAutocompleteElementResponse.fkiDepartmentID == null : this.fkiDepartmentID.equals(customerAutocompleteElementResponse.fkiDepartmentID)) &&
        (this.sCustomerName == null ? customerAutocompleteElementResponse.sCustomerName == null : this.sCustomerName.equals(customerAutocompleteElementResponse.sCustomerName)) &&
        (this.sCustomerCode == null ? customerAutocompleteElementResponse.sCustomerCode == null : this.sCustomerCode.equals(customerAutocompleteElementResponse.sCustomerCode)) &&
        (this.bCustomerIsactive == null ? customerAutocompleteElementResponse.bCustomerIsactive == null : this.bCustomerIsactive.equals(customerAutocompleteElementResponse.bCustomerIsactive));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.pkiCustomerID == null ? 0: this.pkiCustomerID.hashCode());
    result = 31 * result + (this.fkiDepartmentID == null ? 0: this.fkiDepartmentID.hashCode());
    result = 31 * result + (this.sCustomerName == null ? 0: this.sCustomerName.hashCode());
    result = 31 * result + (this.sCustomerCode == null ? 0: this.sCustomerCode.hashCode());
    result = 31 * result + (this.bCustomerIsactive == null ? 0: this.bCustomerIsactive.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerAutocompleteElementResponse {\n");
    
    sb.append("  pkiCustomerID: ").append(pkiCustomerID).append("\n");
    sb.append("  fkiDepartmentID: ").append(fkiDepartmentID).append("\n");
    sb.append("  sCustomerName: ").append(sCustomerName).append("\n");
    sb.append("  sCustomerCode: ").append(sCustomerCode).append("\n");
    sb.append("  bCustomerIsactive: ").append(bCustomerIsactive).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
