/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.CustomContactNameResponse;
import org.openapitools.client.model.EmailResponseCompound;
import org.openapitools.client.model.PhoneResponseCompound;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Generic AutocompleteElement Response
 **/
@ApiModel(description = "Generic AutocompleteElement Response")
public class CustomCommunicationrecipientsrecipientResponse {
  
  @SerializedName("fkiAgentID")
  private Integer fkiAgentID = null;
  @SerializedName("fkiBrokerID")
  private Integer fkiBrokerID = null;
  @SerializedName("fkiContactID")
  private Integer fkiContactID = null;
  @SerializedName("fkiCustomerID")
  private Integer fkiCustomerID = null;
  @SerializedName("fkiEmployeeID")
  private Integer fkiEmployeeID = null;
  @SerializedName("fkiEzsignsignerID")
  private Integer fkiEzsignsignerID = null;
  @SerializedName("fkiFranchiseofficeID")
  private Integer fkiFranchiseofficeID = null;
  @SerializedName("fkiUserID")
  private Integer fkiUserID = null;
  @SerializedName("fkiAgentincorporationID")
  private Integer fkiAgentincorporationID = null;
  @SerializedName("fkiAssistantID")
  private Integer fkiAssistantID = null;
  @SerializedName("fkiExternalbrokerID")
  private Integer fkiExternalbrokerID = null;
  @SerializedName("fkiEzcomagentID")
  private Integer fkiEzcomagentID = null;
  @SerializedName("fkiNotaryID")
  private Integer fkiNotaryID = null;
  @SerializedName("fkiRewardmemberID")
  private Integer fkiRewardmemberID = null;
  @SerializedName("fkiSupplierID")
  private Integer fkiSupplierID = null;
  public enum ECommunicationrecipientsrecipientObjecttypeEnum {
     Agent,  Agentincorporation,  Assistant,  Broker,  Contact,  Customer,  Employee,  Externalbroker,  Ezcomagent,  Ezcomcompany,  Ezsignsigner,  Franchiseoffice,  Notary,  Rewardmember,  Supplier,  User, 
  };
  @SerializedName("eCommunicationrecipientsrecipientObjecttype")
  private ECommunicationrecipientsrecipientObjecttypeEnum eCommunicationrecipientsrecipientObjecttype = null;
  @SerializedName("objContactName")
  private CustomContactNameResponse objContactName = null;
  @SerializedName("objEmail")
  private EmailResponseCompound objEmail = null;
  @SerializedName("objPhoneFax")
  private PhoneResponseCompound objPhoneFax = null;
  @SerializedName("objPhoneSMS")
  private PhoneResponseCompound objPhoneSMS = null;

  /**
   * The unique ID of the Agent.
   * minimum: 0
   **/
  @ApiModelProperty(value = "The unique ID of the Agent.")
  public Integer getFkiAgentID() {
    return fkiAgentID;
  }
  public void setFkiAgentID(Integer fkiAgentID) {
    this.fkiAgentID = fkiAgentID;
  }

  /**
   * The unique ID of the Broker.
   * minimum: 0
   **/
  @ApiModelProperty(value = "The unique ID of the Broker.")
  public Integer getFkiBrokerID() {
    return fkiBrokerID;
  }
  public void setFkiBrokerID(Integer fkiBrokerID) {
    this.fkiBrokerID = fkiBrokerID;
  }

  /**
   * The unique ID of the Contact
   * minimum: 0
   **/
  @ApiModelProperty(value = "The unique ID of the Contact")
  public Integer getFkiContactID() {
    return fkiContactID;
  }
  public void setFkiContactID(Integer fkiContactID) {
    this.fkiContactID = fkiContactID;
  }

  /**
   * The unique ID of the Customer.
   * minimum: 0
   **/
  @ApiModelProperty(value = "The unique ID of the Customer.")
  public Integer getFkiCustomerID() {
    return fkiCustomerID;
  }
  public void setFkiCustomerID(Integer fkiCustomerID) {
    this.fkiCustomerID = fkiCustomerID;
  }

  /**
   * The unique ID of the Employee.
   * minimum: 0
   **/
  @ApiModelProperty(value = "The unique ID of the Employee.")
  public Integer getFkiEmployeeID() {
    return fkiEmployeeID;
  }
  public void setFkiEmployeeID(Integer fkiEmployeeID) {
    this.fkiEmployeeID = fkiEmployeeID;
  }

  /**
   * The unique ID of the Ezsignsigner
   * minimum: 0
   **/
  @ApiModelProperty(value = "The unique ID of the Ezsignsigner")
  public Integer getFkiEzsignsignerID() {
    return fkiEzsignsignerID;
  }
  public void setFkiEzsignsignerID(Integer fkiEzsignsignerID) {
    this.fkiEzsignsignerID = fkiEzsignsignerID;
  }

  /**
   * The unique ID of the Franchisereoffice
   * minimum: 0
   **/
  @ApiModelProperty(value = "The unique ID of the Franchisereoffice")
  public Integer getFkiFranchiseofficeID() {
    return fkiFranchiseofficeID;
  }
  public void setFkiFranchiseofficeID(Integer fkiFranchiseofficeID) {
    this.fkiFranchiseofficeID = fkiFranchiseofficeID;
  }

  /**
   * The unique ID of the User
   * minimum: 0
   **/
  @ApiModelProperty(value = "The unique ID of the User")
  public Integer getFkiUserID() {
    return fkiUserID;
  }
  public void setFkiUserID(Integer fkiUserID) {
    this.fkiUserID = fkiUserID;
  }

  /**
   * The unique ID of the Agentincorporation.
   * minimum: 0
   **/
  @ApiModelProperty(value = "The unique ID of the Agentincorporation.")
  public Integer getFkiAgentincorporationID() {
    return fkiAgentincorporationID;
  }
  public void setFkiAgentincorporationID(Integer fkiAgentincorporationID) {
    this.fkiAgentincorporationID = fkiAgentincorporationID;
  }

  /**
   * The unique ID of the Assistant.
   * minimum: 0
   **/
  @ApiModelProperty(value = "The unique ID of the Assistant.")
  public Integer getFkiAssistantID() {
    return fkiAssistantID;
  }
  public void setFkiAssistantID(Integer fkiAssistantID) {
    this.fkiAssistantID = fkiAssistantID;
  }

  /**
   * The unique ID of the Externalbroker.
   * minimum: 0
   **/
  @ApiModelProperty(value = "The unique ID of the Externalbroker.")
  public Integer getFkiExternalbrokerID() {
    return fkiExternalbrokerID;
  }
  public void setFkiExternalbrokerID(Integer fkiExternalbrokerID) {
    this.fkiExternalbrokerID = fkiExternalbrokerID;
  }

  /**
   * The unique ID of the Ezcomagent.
   * minimum: 0
   **/
  @ApiModelProperty(value = "The unique ID of the Ezcomagent.")
  public Integer getFkiEzcomagentID() {
    return fkiEzcomagentID;
  }
  public void setFkiEzcomagentID(Integer fkiEzcomagentID) {
    this.fkiEzcomagentID = fkiEzcomagentID;
  }

  /**
   * The unique ID of the Notary.
   * minimum: 0
   **/
  @ApiModelProperty(value = "The unique ID of the Notary.")
  public Integer getFkiNotaryID() {
    return fkiNotaryID;
  }
  public void setFkiNotaryID(Integer fkiNotaryID) {
    this.fkiNotaryID = fkiNotaryID;
  }

  /**
   * The unique ID of the Rewardmember.
   * minimum: 0
   **/
  @ApiModelProperty(value = "The unique ID of the Rewardmember.")
  public Integer getFkiRewardmemberID() {
    return fkiRewardmemberID;
  }
  public void setFkiRewardmemberID(Integer fkiRewardmemberID) {
    this.fkiRewardmemberID = fkiRewardmemberID;
  }

  /**
   * The unique ID of the Supplier.
   * minimum: 0
   **/
  @ApiModelProperty(value = "The unique ID of the Supplier.")
  public Integer getFkiSupplierID() {
    return fkiSupplierID;
  }
  public void setFkiSupplierID(Integer fkiSupplierID) {
    this.fkiSupplierID = fkiSupplierID;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public ECommunicationrecipientsrecipientObjecttypeEnum getECommunicationrecipientsrecipientObjecttype() {
    return eCommunicationrecipientsrecipientObjecttype;
  }
  public void setECommunicationrecipientsrecipientObjecttype(ECommunicationrecipientsrecipientObjecttypeEnum eCommunicationrecipientsrecipientObjecttype) {
    this.eCommunicationrecipientsrecipientObjecttype = eCommunicationrecipientsrecipientObjecttype;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public CustomContactNameResponse getObjContactName() {
    return objContactName;
  }
  public void setObjContactName(CustomContactNameResponse objContactName) {
    this.objContactName = objContactName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public EmailResponseCompound getObjEmail() {
    return objEmail;
  }
  public void setObjEmail(EmailResponseCompound objEmail) {
    this.objEmail = objEmail;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public PhoneResponseCompound getObjPhoneFax() {
    return objPhoneFax;
  }
  public void setObjPhoneFax(PhoneResponseCompound objPhoneFax) {
    this.objPhoneFax = objPhoneFax;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public PhoneResponseCompound getObjPhoneSMS() {
    return objPhoneSMS;
  }
  public void setObjPhoneSMS(PhoneResponseCompound objPhoneSMS) {
    this.objPhoneSMS = objPhoneSMS;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomCommunicationrecipientsrecipientResponse customCommunicationrecipientsrecipientResponse = (CustomCommunicationrecipientsrecipientResponse) o;
    return (this.fkiAgentID == null ? customCommunicationrecipientsrecipientResponse.fkiAgentID == null : this.fkiAgentID.equals(customCommunicationrecipientsrecipientResponse.fkiAgentID)) &&
        (this.fkiBrokerID == null ? customCommunicationrecipientsrecipientResponse.fkiBrokerID == null : this.fkiBrokerID.equals(customCommunicationrecipientsrecipientResponse.fkiBrokerID)) &&
        (this.fkiContactID == null ? customCommunicationrecipientsrecipientResponse.fkiContactID == null : this.fkiContactID.equals(customCommunicationrecipientsrecipientResponse.fkiContactID)) &&
        (this.fkiCustomerID == null ? customCommunicationrecipientsrecipientResponse.fkiCustomerID == null : this.fkiCustomerID.equals(customCommunicationrecipientsrecipientResponse.fkiCustomerID)) &&
        (this.fkiEmployeeID == null ? customCommunicationrecipientsrecipientResponse.fkiEmployeeID == null : this.fkiEmployeeID.equals(customCommunicationrecipientsrecipientResponse.fkiEmployeeID)) &&
        (this.fkiEzsignsignerID == null ? customCommunicationrecipientsrecipientResponse.fkiEzsignsignerID == null : this.fkiEzsignsignerID.equals(customCommunicationrecipientsrecipientResponse.fkiEzsignsignerID)) &&
        (this.fkiFranchiseofficeID == null ? customCommunicationrecipientsrecipientResponse.fkiFranchiseofficeID == null : this.fkiFranchiseofficeID.equals(customCommunicationrecipientsrecipientResponse.fkiFranchiseofficeID)) &&
        (this.fkiUserID == null ? customCommunicationrecipientsrecipientResponse.fkiUserID == null : this.fkiUserID.equals(customCommunicationrecipientsrecipientResponse.fkiUserID)) &&
        (this.fkiAgentincorporationID == null ? customCommunicationrecipientsrecipientResponse.fkiAgentincorporationID == null : this.fkiAgentincorporationID.equals(customCommunicationrecipientsrecipientResponse.fkiAgentincorporationID)) &&
        (this.fkiAssistantID == null ? customCommunicationrecipientsrecipientResponse.fkiAssistantID == null : this.fkiAssistantID.equals(customCommunicationrecipientsrecipientResponse.fkiAssistantID)) &&
        (this.fkiExternalbrokerID == null ? customCommunicationrecipientsrecipientResponse.fkiExternalbrokerID == null : this.fkiExternalbrokerID.equals(customCommunicationrecipientsrecipientResponse.fkiExternalbrokerID)) &&
        (this.fkiEzcomagentID == null ? customCommunicationrecipientsrecipientResponse.fkiEzcomagentID == null : this.fkiEzcomagentID.equals(customCommunicationrecipientsrecipientResponse.fkiEzcomagentID)) &&
        (this.fkiNotaryID == null ? customCommunicationrecipientsrecipientResponse.fkiNotaryID == null : this.fkiNotaryID.equals(customCommunicationrecipientsrecipientResponse.fkiNotaryID)) &&
        (this.fkiRewardmemberID == null ? customCommunicationrecipientsrecipientResponse.fkiRewardmemberID == null : this.fkiRewardmemberID.equals(customCommunicationrecipientsrecipientResponse.fkiRewardmemberID)) &&
        (this.fkiSupplierID == null ? customCommunicationrecipientsrecipientResponse.fkiSupplierID == null : this.fkiSupplierID.equals(customCommunicationrecipientsrecipientResponse.fkiSupplierID)) &&
        (this.eCommunicationrecipientsrecipientObjecttype == null ? customCommunicationrecipientsrecipientResponse.eCommunicationrecipientsrecipientObjecttype == null : this.eCommunicationrecipientsrecipientObjecttype.equals(customCommunicationrecipientsrecipientResponse.eCommunicationrecipientsrecipientObjecttype)) &&
        (this.objContactName == null ? customCommunicationrecipientsrecipientResponse.objContactName == null : this.objContactName.equals(customCommunicationrecipientsrecipientResponse.objContactName)) &&
        (this.objEmail == null ? customCommunicationrecipientsrecipientResponse.objEmail == null : this.objEmail.equals(customCommunicationrecipientsrecipientResponse.objEmail)) &&
        (this.objPhoneFax == null ? customCommunicationrecipientsrecipientResponse.objPhoneFax == null : this.objPhoneFax.equals(customCommunicationrecipientsrecipientResponse.objPhoneFax)) &&
        (this.objPhoneSMS == null ? customCommunicationrecipientsrecipientResponse.objPhoneSMS == null : this.objPhoneSMS.equals(customCommunicationrecipientsrecipientResponse.objPhoneSMS));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.fkiAgentID == null ? 0: this.fkiAgentID.hashCode());
    result = 31 * result + (this.fkiBrokerID == null ? 0: this.fkiBrokerID.hashCode());
    result = 31 * result + (this.fkiContactID == null ? 0: this.fkiContactID.hashCode());
    result = 31 * result + (this.fkiCustomerID == null ? 0: this.fkiCustomerID.hashCode());
    result = 31 * result + (this.fkiEmployeeID == null ? 0: this.fkiEmployeeID.hashCode());
    result = 31 * result + (this.fkiEzsignsignerID == null ? 0: this.fkiEzsignsignerID.hashCode());
    result = 31 * result + (this.fkiFranchiseofficeID == null ? 0: this.fkiFranchiseofficeID.hashCode());
    result = 31 * result + (this.fkiUserID == null ? 0: this.fkiUserID.hashCode());
    result = 31 * result + (this.fkiAgentincorporationID == null ? 0: this.fkiAgentincorporationID.hashCode());
    result = 31 * result + (this.fkiAssistantID == null ? 0: this.fkiAssistantID.hashCode());
    result = 31 * result + (this.fkiExternalbrokerID == null ? 0: this.fkiExternalbrokerID.hashCode());
    result = 31 * result + (this.fkiEzcomagentID == null ? 0: this.fkiEzcomagentID.hashCode());
    result = 31 * result + (this.fkiNotaryID == null ? 0: this.fkiNotaryID.hashCode());
    result = 31 * result + (this.fkiRewardmemberID == null ? 0: this.fkiRewardmemberID.hashCode());
    result = 31 * result + (this.fkiSupplierID == null ? 0: this.fkiSupplierID.hashCode());
    result = 31 * result + (this.eCommunicationrecipientsrecipientObjecttype == null ? 0: this.eCommunicationrecipientsrecipientObjecttype.hashCode());
    result = 31 * result + (this.objContactName == null ? 0: this.objContactName.hashCode());
    result = 31 * result + (this.objEmail == null ? 0: this.objEmail.hashCode());
    result = 31 * result + (this.objPhoneFax == null ? 0: this.objPhoneFax.hashCode());
    result = 31 * result + (this.objPhoneSMS == null ? 0: this.objPhoneSMS.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomCommunicationrecipientsrecipientResponse {\n");
    
    sb.append("  fkiAgentID: ").append(fkiAgentID).append("\n");
    sb.append("  fkiBrokerID: ").append(fkiBrokerID).append("\n");
    sb.append("  fkiContactID: ").append(fkiContactID).append("\n");
    sb.append("  fkiCustomerID: ").append(fkiCustomerID).append("\n");
    sb.append("  fkiEmployeeID: ").append(fkiEmployeeID).append("\n");
    sb.append("  fkiEzsignsignerID: ").append(fkiEzsignsignerID).append("\n");
    sb.append("  fkiFranchiseofficeID: ").append(fkiFranchiseofficeID).append("\n");
    sb.append("  fkiUserID: ").append(fkiUserID).append("\n");
    sb.append("  fkiAgentincorporationID: ").append(fkiAgentincorporationID).append("\n");
    sb.append("  fkiAssistantID: ").append(fkiAssistantID).append("\n");
    sb.append("  fkiExternalbrokerID: ").append(fkiExternalbrokerID).append("\n");
    sb.append("  fkiEzcomagentID: ").append(fkiEzcomagentID).append("\n");
    sb.append("  fkiNotaryID: ").append(fkiNotaryID).append("\n");
    sb.append("  fkiRewardmemberID: ").append(fkiRewardmemberID).append("\n");
    sb.append("  fkiSupplierID: ").append(fkiSupplierID).append("\n");
    sb.append("  eCommunicationrecipientsrecipientObjecttype: ").append(eCommunicationrecipientsrecipientObjecttype).append("\n");
    sb.append("  objContactName: ").append(objContactName).append("\n");
    sb.append("  objEmail: ").append(objEmail).append("\n");
    sb.append("  objPhoneFax: ").append(objPhoneFax).append("\n");
    sb.append("  objPhoneSMS: ").append(objPhoneSMS).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
