/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Request for POST /1/object/discussion/{pkiDiscussionID}/updateDiscussionreadstatus
 **/
@ApiModel(description = "Request for POST /1/object/discussion/{pkiDiscussionID}/updateDiscussionreadstatus")
public class DiscussionUpdateDiscussionreadstatusV1Request {
  
  @SerializedName("dtDiscussionreadstatusDate")
  private String dtDiscussionreadstatusDate = null;

  /**
   * The date of the last discussion message read
   **/
  @ApiModelProperty(value = "The date of the last discussion message read")
  public String getDtDiscussionreadstatusDate() {
    return dtDiscussionreadstatusDate;
  }
  public void setDtDiscussionreadstatusDate(String dtDiscussionreadstatusDate) {
    this.dtDiscussionreadstatusDate = dtDiscussionreadstatusDate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DiscussionUpdateDiscussionreadstatusV1Request discussionUpdateDiscussionreadstatusV1Request = (DiscussionUpdateDiscussionreadstatusV1Request) o;
    return (this.dtDiscussionreadstatusDate == null ? discussionUpdateDiscussionreadstatusV1Request.dtDiscussionreadstatusDate == null : this.dtDiscussionreadstatusDate.equals(discussionUpdateDiscussionreadstatusV1Request.dtDiscussionreadstatusDate));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.dtDiscussionreadstatusDate == null ? 0: this.dtDiscussionreadstatusDate.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DiscussionUpdateDiscussionreadstatusV1Request {\n");
    
    sb.append("  dtDiscussionreadstatusDate: ").append(dtDiscussionreadstatusDate).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
