/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.CustomDiscussionconfigurationResponse;
import org.openapitools.client.model.DiscussionmembershipResponseCompound;
import org.openapitools.client.model.DiscussionmessageResponseCompound;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * A Discussion Object
 **/
@ApiModel(description = "A Discussion Object")
public class DiscussionResponseCompound {
  
  @SerializedName("pkiDiscussionID")
  private Integer pkiDiscussionID = null;
  @SerializedName("sDiscussionDescription")
  private String sDiscussionDescription = null;
  @SerializedName("bDiscussionClosed")
  private Boolean bDiscussionClosed = null;
  @SerializedName("dtDiscussionLastread")
  private String dtDiscussionLastread = null;
  @SerializedName("iDiscussionmessageCount")
  private Integer iDiscussionmessageCount = null;
  @SerializedName("iDiscussionmessageCountunread")
  private Integer iDiscussionmessageCountunread = null;
  @SerializedName("objDiscussionconfiguration")
  private CustomDiscussionconfigurationResponse objDiscussionconfiguration = null;
  @SerializedName("a_objDiscussionmembership")
  private List<DiscussionmembershipResponseCompound> aObjDiscussionmembership = null;
  @SerializedName("a_objDiscussionmessage")
  private List<DiscussionmessageResponseCompound> aObjDiscussionmessage = null;

  /**
   * The unique ID of the Discussion
   * minimum: 0
   * maximum: 16777215
   **/
  @ApiModelProperty(required = true, value = "The unique ID of the Discussion")
  public Integer getPkiDiscussionID() {
    return pkiDiscussionID;
  }
  public void setPkiDiscussionID(Integer pkiDiscussionID) {
    this.pkiDiscussionID = pkiDiscussionID;
  }

  /**
   * The description of the Discussion
   **/
  @ApiModelProperty(required = true, value = "The description of the Discussion")
  public String getSDiscussionDescription() {
    return sDiscussionDescription;
  }
  public void setSDiscussionDescription(String sDiscussionDescription) {
    this.sDiscussionDescription = sDiscussionDescription;
  }

  /**
   * Whether if it's an closed
   **/
  @ApiModelProperty(required = true, value = "Whether if it's an closed")
  public Boolean getBDiscussionClosed() {
    return bDiscussionClosed;
  }
  public void setBDiscussionClosed(Boolean bDiscussionClosed) {
    this.bDiscussionClosed = bDiscussionClosed;
  }

  /**
   * The date the Discussion was last read
   **/
  @ApiModelProperty(value = "The date the Discussion was last read")
  public String getDtDiscussionLastread() {
    return dtDiscussionLastread;
  }
  public void setDtDiscussionLastread(String dtDiscussionLastread) {
    this.dtDiscussionLastread = dtDiscussionLastread;
  }

  /**
   * The count of Attachment.
   **/
  @ApiModelProperty(required = true, value = "The count of Attachment.")
  public Integer getIDiscussionmessageCount() {
    return iDiscussionmessageCount;
  }
  public void setIDiscussionmessageCount(Integer iDiscussionmessageCount) {
    this.iDiscussionmessageCount = iDiscussionmessageCount;
  }

  /**
   * The count of Attachment.
   **/
  @ApiModelProperty(required = true, value = "The count of Attachment.")
  public Integer getIDiscussionmessageCountunread() {
    return iDiscussionmessageCountunread;
  }
  public void setIDiscussionmessageCountunread(Integer iDiscussionmessageCountunread) {
    this.iDiscussionmessageCountunread = iDiscussionmessageCountunread;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public CustomDiscussionconfigurationResponse getObjDiscussionconfiguration() {
    return objDiscussionconfiguration;
  }
  public void setObjDiscussionconfiguration(CustomDiscussionconfigurationResponse objDiscussionconfiguration) {
    this.objDiscussionconfiguration = objDiscussionconfiguration;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<DiscussionmembershipResponseCompound> getAObjDiscussionmembership() {
    return aObjDiscussionmembership;
  }
  public void setAObjDiscussionmembership(List<DiscussionmembershipResponseCompound> aObjDiscussionmembership) {
    this.aObjDiscussionmembership = aObjDiscussionmembership;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<DiscussionmessageResponseCompound> getAObjDiscussionmessage() {
    return aObjDiscussionmessage;
  }
  public void setAObjDiscussionmessage(List<DiscussionmessageResponseCompound> aObjDiscussionmessage) {
    this.aObjDiscussionmessage = aObjDiscussionmessage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DiscussionResponseCompound discussionResponseCompound = (DiscussionResponseCompound) o;
    return (this.pkiDiscussionID == null ? discussionResponseCompound.pkiDiscussionID == null : this.pkiDiscussionID.equals(discussionResponseCompound.pkiDiscussionID)) &&
        (this.sDiscussionDescription == null ? discussionResponseCompound.sDiscussionDescription == null : this.sDiscussionDescription.equals(discussionResponseCompound.sDiscussionDescription)) &&
        (this.bDiscussionClosed == null ? discussionResponseCompound.bDiscussionClosed == null : this.bDiscussionClosed.equals(discussionResponseCompound.bDiscussionClosed)) &&
        (this.dtDiscussionLastread == null ? discussionResponseCompound.dtDiscussionLastread == null : this.dtDiscussionLastread.equals(discussionResponseCompound.dtDiscussionLastread)) &&
        (this.iDiscussionmessageCount == null ? discussionResponseCompound.iDiscussionmessageCount == null : this.iDiscussionmessageCount.equals(discussionResponseCompound.iDiscussionmessageCount)) &&
        (this.iDiscussionmessageCountunread == null ? discussionResponseCompound.iDiscussionmessageCountunread == null : this.iDiscussionmessageCountunread.equals(discussionResponseCompound.iDiscussionmessageCountunread)) &&
        (this.objDiscussionconfiguration == null ? discussionResponseCompound.objDiscussionconfiguration == null : this.objDiscussionconfiguration.equals(discussionResponseCompound.objDiscussionconfiguration)) &&
        (this.aObjDiscussionmembership == null ? discussionResponseCompound.aObjDiscussionmembership == null : this.aObjDiscussionmembership.equals(discussionResponseCompound.aObjDiscussionmembership)) &&
        (this.aObjDiscussionmessage == null ? discussionResponseCompound.aObjDiscussionmessage == null : this.aObjDiscussionmessage.equals(discussionResponseCompound.aObjDiscussionmessage));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.pkiDiscussionID == null ? 0: this.pkiDiscussionID.hashCode());
    result = 31 * result + (this.sDiscussionDescription == null ? 0: this.sDiscussionDescription.hashCode());
    result = 31 * result + (this.bDiscussionClosed == null ? 0: this.bDiscussionClosed.hashCode());
    result = 31 * result + (this.dtDiscussionLastread == null ? 0: this.dtDiscussionLastread.hashCode());
    result = 31 * result + (this.iDiscussionmessageCount == null ? 0: this.iDiscussionmessageCount.hashCode());
    result = 31 * result + (this.iDiscussionmessageCountunread == null ? 0: this.iDiscussionmessageCountunread.hashCode());
    result = 31 * result + (this.objDiscussionconfiguration == null ? 0: this.objDiscussionconfiguration.hashCode());
    result = 31 * result + (this.aObjDiscussionmembership == null ? 0: this.aObjDiscussionmembership.hashCode());
    result = 31 * result + (this.aObjDiscussionmessage == null ? 0: this.aObjDiscussionmessage.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DiscussionResponseCompound {\n");
    
    sb.append("  pkiDiscussionID: ").append(pkiDiscussionID).append("\n");
    sb.append("  sDiscussionDescription: ").append(sDiscussionDescription).append("\n");
    sb.append("  bDiscussionClosed: ").append(bDiscussionClosed).append("\n");
    sb.append("  dtDiscussionLastread: ").append(dtDiscussionLastread).append("\n");
    sb.append("  iDiscussionmessageCount: ").append(iDiscussionmessageCount).append("\n");
    sb.append("  iDiscussionmessageCountunread: ").append(iDiscussionmessageCountunread).append("\n");
    sb.append("  objDiscussionconfiguration: ").append(objDiscussionconfiguration).append("\n");
    sb.append("  aObjDiscussionmembership: ").append(aObjDiscussionmembership).append("\n");
    sb.append("  aObjDiscussionmessage: ").append(aObjDiscussionmessage).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
