/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.EzdoctemplatetypeAutocompleteElementResponse;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Payload for POST /2/object/ezdoctemplatetype/getAutocomplete
 **/
@ApiModel(description = "Payload for POST /2/object/ezdoctemplatetype/getAutocomplete")
public class EzdoctemplatetypeGetAutocompleteV2ResponseMPayload {
  
  @SerializedName("a_objEzdoctemplatetype")
  private List<EzdoctemplatetypeAutocompleteElementResponse> aObjEzdoctemplatetype = null;

  /**
   * An array of Ezdoctemplatetype autocomplete element response.
   **/
  @ApiModelProperty(required = true, value = "An array of Ezdoctemplatetype autocomplete element response.")
  public List<EzdoctemplatetypeAutocompleteElementResponse> getAObjEzdoctemplatetype() {
    return aObjEzdoctemplatetype;
  }
  public void setAObjEzdoctemplatetype(List<EzdoctemplatetypeAutocompleteElementResponse> aObjEzdoctemplatetype) {
    this.aObjEzdoctemplatetype = aObjEzdoctemplatetype;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EzdoctemplatetypeGetAutocompleteV2ResponseMPayload ezdoctemplatetypeGetAutocompleteV2ResponseMPayload = (EzdoctemplatetypeGetAutocompleteV2ResponseMPayload) o;
    return (this.aObjEzdoctemplatetype == null ? ezdoctemplatetypeGetAutocompleteV2ResponseMPayload.aObjEzdoctemplatetype == null : this.aObjEzdoctemplatetype.equals(ezdoctemplatetypeGetAutocompleteV2ResponseMPayload.aObjEzdoctemplatetype));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.aObjEzdoctemplatetype == null ? 0: this.aObjEzdoctemplatetype.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class EzdoctemplatetypeGetAutocompleteV2ResponseMPayload {\n");
    
    sb.append("  aObjEzdoctemplatetype: ").append(aObjEzdoctemplatetype).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
