/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.EzsignfoldertypeRequestCompoundV2;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Request for PUT /2/object/ezsignfoldertype/{pkiEzsignfoldertypeID}
 **/
@ApiModel(description = "Request for PUT /2/object/ezsignfoldertype/{pkiEzsignfoldertypeID}")
public class EzsignfoldertypeEditObjectV2Request {
  
  @SerializedName("objEzsignfoldertype")
  private EzsignfoldertypeRequestCompoundV2 objEzsignfoldertype = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public EzsignfoldertypeRequestCompoundV2 getObjEzsignfoldertype() {
    return objEzsignfoldertype;
  }
  public void setObjEzsignfoldertype(EzsignfoldertypeRequestCompoundV2 objEzsignfoldertype) {
    this.objEzsignfoldertype = objEzsignfoldertype;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EzsignfoldertypeEditObjectV2Request ezsignfoldertypeEditObjectV2Request = (EzsignfoldertypeEditObjectV2Request) o;
    return (this.objEzsignfoldertype == null ? ezsignfoldertypeEditObjectV2Request.objEzsignfoldertype == null : this.objEzsignfoldertype.equals(ezsignfoldertypeEditObjectV2Request.objEzsignfoldertype));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.objEzsignfoldertype == null ? 0: this.objEzsignfoldertype.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class EzsignfoldertypeEditObjectV2Request {\n");
    
    sb.append("  objEzsignfoldertype: ").append(objEzsignfoldertype).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
