/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.12
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class EzsignfoldertypeRequestCompoundAllOf {
  
  @SerializedName("a_fkiUserIDSigned")
  private List<Integer> aFkiUserIDSigned = null;
  @SerializedName("a_fkiUserIDSummary")
  private List<Integer> aFkiUserIDSummary = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Integer> getAFkiUserIDSigned() {
    return aFkiUserIDSigned;
  }
  public void setAFkiUserIDSigned(List<Integer> aFkiUserIDSigned) {
    this.aFkiUserIDSigned = aFkiUserIDSigned;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Integer> getAFkiUserIDSummary() {
    return aFkiUserIDSummary;
  }
  public void setAFkiUserIDSummary(List<Integer> aFkiUserIDSummary) {
    this.aFkiUserIDSummary = aFkiUserIDSummary;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EzsignfoldertypeRequestCompoundAllOf ezsignfoldertypeRequestCompoundAllOf = (EzsignfoldertypeRequestCompoundAllOf) o;
    return (this.aFkiUserIDSigned == null ? ezsignfoldertypeRequestCompoundAllOf.aFkiUserIDSigned == null : this.aFkiUserIDSigned.equals(ezsignfoldertypeRequestCompoundAllOf.aFkiUserIDSigned)) &&
        (this.aFkiUserIDSummary == null ? ezsignfoldertypeRequestCompoundAllOf.aFkiUserIDSummary == null : this.aFkiUserIDSummary.equals(ezsignfoldertypeRequestCompoundAllOf.aFkiUserIDSummary));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.aFkiUserIDSigned == null ? 0: this.aFkiUserIDSigned.hashCode());
    result = 31 * result + (this.aFkiUserIDSummary == null ? 0: this.aFkiUserIDSummary.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class EzsignfoldertypeRequestCompoundAllOf {\n");
    
    sb.append("  aFkiUserIDSigned: ").append(aFkiUserIDSigned).append("\n");
    sb.append("  aFkiUserIDSummary: ").append(aFkiUserIDSummary).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
