/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.3.2
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.FieldEEzsignsignaturepaymentdetailTaxable;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * An Ezsignsignaturepaymentdetail Object and children to create a complete structure
 **/
@ApiModel(description = "An Ezsignsignaturepaymentdetail Object and children to create a complete structure")
public class EzsignsignaturepaymentdetailResponseCompound {
  
  @SerializedName("pkiEzsignsignaturepaymentdetailID")
  private Integer pkiEzsignsignaturepaymentdetailID = null;
  @SerializedName("fkiGlaccountcontainerID")
  private Integer fkiGlaccountcontainerID = null;
  @SerializedName("tEzsignsignaturepaymentdetailDescription")
  private String tEzsignsignaturepaymentdetailDescription = null;
  @SerializedName("dEzsignsignaturepaymentdetailAmount")
  private String dEzsignsignaturepaymentdetailAmount = null;
  @SerializedName("eEzsignsignaturepaymentdetailTaxable")
  private FieldEEzsignsignaturepaymentdetailTaxable eEzsignsignaturepaymentdetailTaxable = null;

  /**
   * The unique ID of the Ezsignsignaturepaymentdetail
   * minimum: 0
   * maximum: 65535
   **/
  @ApiModelProperty(required = true, value = "The unique ID of the Ezsignsignaturepaymentdetail")
  public Integer getPkiEzsignsignaturepaymentdetailID() {
    return pkiEzsignsignaturepaymentdetailID;
  }
  public void setPkiEzsignsignaturepaymentdetailID(Integer pkiEzsignsignaturepaymentdetailID) {
    this.pkiEzsignsignaturepaymentdetailID = pkiEzsignsignaturepaymentdetailID;
  }

  /**
   * The unique ID of the Glaccountcontainer
   * minimum: 0
   **/
  @ApiModelProperty(value = "The unique ID of the Glaccountcontainer")
  public Integer getFkiGlaccountcontainerID() {
    return fkiGlaccountcontainerID;
  }
  public void setFkiGlaccountcontainerID(Integer fkiGlaccountcontainerID) {
    this.fkiGlaccountcontainerID = fkiGlaccountcontainerID;
  }

  /**
   * A description for the Ezsignsignaturepaymentdetail.
   **/
  @ApiModelProperty(required = true, value = "A description for the Ezsignsignaturepaymentdetail.")
  public String getTEzsignsignaturepaymentdetailDescription() {
    return tEzsignsignaturepaymentdetailDescription;
  }
  public void setTEzsignsignaturepaymentdetailDescription(String tEzsignsignaturepaymentdetailDescription) {
    this.tEzsignsignaturepaymentdetailDescription = tEzsignsignaturepaymentdetailDescription;
  }

  /**
   * The amount of the for the Ezsignsignaturepaymentdetail
   **/
  @ApiModelProperty(required = true, value = "The amount of the for the Ezsignsignaturepaymentdetail")
  public String getDEzsignsignaturepaymentdetailAmount() {
    return dEzsignsignaturepaymentdetailAmount;
  }
  public void setDEzsignsignaturepaymentdetailAmount(String dEzsignsignaturepaymentdetailAmount) {
    this.dEzsignsignaturepaymentdetailAmount = dEzsignsignaturepaymentdetailAmount;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public FieldEEzsignsignaturepaymentdetailTaxable getEEzsignsignaturepaymentdetailTaxable() {
    return eEzsignsignaturepaymentdetailTaxable;
  }
  public void setEEzsignsignaturepaymentdetailTaxable(FieldEEzsignsignaturepaymentdetailTaxable eEzsignsignaturepaymentdetailTaxable) {
    this.eEzsignsignaturepaymentdetailTaxable = eEzsignsignaturepaymentdetailTaxable;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EzsignsignaturepaymentdetailResponseCompound ezsignsignaturepaymentdetailResponseCompound = (EzsignsignaturepaymentdetailResponseCompound) o;
    return (this.pkiEzsignsignaturepaymentdetailID == null ? ezsignsignaturepaymentdetailResponseCompound.pkiEzsignsignaturepaymentdetailID == null : this.pkiEzsignsignaturepaymentdetailID.equals(ezsignsignaturepaymentdetailResponseCompound.pkiEzsignsignaturepaymentdetailID)) &&
        (this.fkiGlaccountcontainerID == null ? ezsignsignaturepaymentdetailResponseCompound.fkiGlaccountcontainerID == null : this.fkiGlaccountcontainerID.equals(ezsignsignaturepaymentdetailResponseCompound.fkiGlaccountcontainerID)) &&
        (this.tEzsignsignaturepaymentdetailDescription == null ? ezsignsignaturepaymentdetailResponseCompound.tEzsignsignaturepaymentdetailDescription == null : this.tEzsignsignaturepaymentdetailDescription.equals(ezsignsignaturepaymentdetailResponseCompound.tEzsignsignaturepaymentdetailDescription)) &&
        (this.dEzsignsignaturepaymentdetailAmount == null ? ezsignsignaturepaymentdetailResponseCompound.dEzsignsignaturepaymentdetailAmount == null : this.dEzsignsignaturepaymentdetailAmount.equals(ezsignsignaturepaymentdetailResponseCompound.dEzsignsignaturepaymentdetailAmount)) &&
        (this.eEzsignsignaturepaymentdetailTaxable == null ? ezsignsignaturepaymentdetailResponseCompound.eEzsignsignaturepaymentdetailTaxable == null : this.eEzsignsignaturepaymentdetailTaxable.equals(ezsignsignaturepaymentdetailResponseCompound.eEzsignsignaturepaymentdetailTaxable));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.pkiEzsignsignaturepaymentdetailID == null ? 0: this.pkiEzsignsignaturepaymentdetailID.hashCode());
    result = 31 * result + (this.fkiGlaccountcontainerID == null ? 0: this.fkiGlaccountcontainerID.hashCode());
    result = 31 * result + (this.tEzsignsignaturepaymentdetailDescription == null ? 0: this.tEzsignsignaturepaymentdetailDescription.hashCode());
    result = 31 * result + (this.dEzsignsignaturepaymentdetailAmount == null ? 0: this.dEzsignsignaturepaymentdetailAmount.hashCode());
    result = 31 * result + (this.eEzsignsignaturepaymentdetailTaxable == null ? 0: this.eEzsignsignaturepaymentdetailTaxable.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class EzsignsignaturepaymentdetailResponseCompound {\n");
    
    sb.append("  pkiEzsignsignaturepaymentdetailID: ").append(pkiEzsignsignaturepaymentdetailID).append("\n");
    sb.append("  fkiGlaccountcontainerID: ").append(fkiGlaccountcontainerID).append("\n");
    sb.append("  tEzsignsignaturepaymentdetailDescription: ").append(tEzsignsignaturepaymentdetailDescription).append("\n");
    sb.append("  dEzsignsignaturepaymentdetailAmount: ").append(dEzsignsignaturepaymentdetailAmount).append("\n");
    sb.append("  eEzsignsignaturepaymentdetailTaxable: ").append(eEzsignsignaturepaymentdetailTaxable).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
