/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Payload for POST /1/object/ezsigndiscussion
 **/
@ApiModel(description = "Payload for POST /1/object/ezsigndiscussion")
public class EzsigndiscussionCreateObjectV1ResponseMPayload {
  
  @SerializedName("a_pkiEzsigndiscussionID")
  private List<Integer> aPkiEzsigndiscussionID = null;

  /**
   * An array of unique IDs representing the object that were requested to be created.  They are returned in the same order as the array containing the objects to be created that was sent in the request.
   **/
  @ApiModelProperty(required = true, value = "An array of unique IDs representing the object that were requested to be created.  They are returned in the same order as the array containing the objects to be created that was sent in the request.")
  public List<Integer> getAPkiEzsigndiscussionID() {
    return aPkiEzsigndiscussionID;
  }
  public void setAPkiEzsigndiscussionID(List<Integer> aPkiEzsigndiscussionID) {
    this.aPkiEzsigndiscussionID = aPkiEzsigndiscussionID;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EzsigndiscussionCreateObjectV1ResponseMPayload ezsigndiscussionCreateObjectV1ResponseMPayload = (EzsigndiscussionCreateObjectV1ResponseMPayload) o;
    return (this.aPkiEzsigndiscussionID == null ? ezsigndiscussionCreateObjectV1ResponseMPayload.aPkiEzsigndiscussionID == null : this.aPkiEzsigndiscussionID.equals(ezsigndiscussionCreateObjectV1ResponseMPayload.aPkiEzsigndiscussionID));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.aPkiEzsigndiscussionID == null ? 0: this.aPkiEzsigndiscussionID.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class EzsigndiscussionCreateObjectV1ResponseMPayload {\n");
    
    sb.append("  aPkiEzsigndiscussionID: ").append(aPkiEzsigndiscussionID).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
