/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Payload for POST /1/object/ezsignsigningreason
 **/
@ApiModel(description = "Payload for POST /1/object/ezsignsigningreason")
public class EzsignsigningreasonCreateObjectV1ResponseMPayload {
  
  @SerializedName("a_pkiEzsignsigningreasonID")
  private List<Integer> aPkiEzsignsigningreasonID = null;

  /**
   * An array of unique IDs representing the object that were requested to be created.  They are returned in the same order as the array containing the objects to be created that was sent in the request.
   **/
  @ApiModelProperty(required = true, value = "An array of unique IDs representing the object that were requested to be created.  They are returned in the same order as the array containing the objects to be created that was sent in the request.")
  public List<Integer> getAPkiEzsignsigningreasonID() {
    return aPkiEzsignsigningreasonID;
  }
  public void setAPkiEzsignsigningreasonID(List<Integer> aPkiEzsignsigningreasonID) {
    this.aPkiEzsignsigningreasonID = aPkiEzsignsigningreasonID;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EzsignsigningreasonCreateObjectV1ResponseMPayload ezsignsigningreasonCreateObjectV1ResponseMPayload = (EzsignsigningreasonCreateObjectV1ResponseMPayload) o;
    return (this.aPkiEzsignsigningreasonID == null ? ezsignsigningreasonCreateObjectV1ResponseMPayload.aPkiEzsignsigningreasonID == null : this.aPkiEzsignsigningreasonID.equals(ezsignsigningreasonCreateObjectV1ResponseMPayload.aPkiEzsignsigningreasonID));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.aPkiEzsignsigningreasonID == null ? 0: this.aPkiEzsignsigningreasonID.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class EzsignsigningreasonCreateObjectV1ResponseMPayload {\n");
    
    sb.append("  aPkiEzsignsigningreasonID: ").append(aPkiEzsignsigningreasonID).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
