/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.FieldEEzsigntemplatesignaturepaymentdetailTaxable;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * An Ezsigntemplatesignaturepaymentdetail Object and children to create a complete structure
 **/
@ApiModel(description = "An Ezsigntemplatesignaturepaymentdetail Object and children to create a complete structure")
public class EzsigntemplatesignaturepaymentdetailRequestCompound {
  
  @SerializedName("pkiEzsigntemplatesignaturepaymentdetailID")
  private Integer pkiEzsigntemplatesignaturepaymentdetailID = null;
  @SerializedName("fkiGlaccountcontainerID")
  private Integer fkiGlaccountcontainerID = null;
  @SerializedName("tEzsigntemplatesignaturepaymentdetailDescription")
  private String tEzsigntemplatesignaturepaymentdetailDescription = null;
  @SerializedName("dEzsigntemplatesignaturepaymentdetailAmount")
  private String dEzsigntemplatesignaturepaymentdetailAmount = null;
  @SerializedName("eEzsigntemplatesignaturepaymentdetailTaxable")
  private FieldEEzsigntemplatesignaturepaymentdetailTaxable eEzsigntemplatesignaturepaymentdetailTaxable = null;

  /**
   * The unique ID of the Ezsignsignaturepaymentdetail
   * minimum: 0
   * maximum: 65535
   **/
  @ApiModelProperty(value = "The unique ID of the Ezsignsignaturepaymentdetail")
  public Integer getPkiEzsigntemplatesignaturepaymentdetailID() {
    return pkiEzsigntemplatesignaturepaymentdetailID;
  }
  public void setPkiEzsigntemplatesignaturepaymentdetailID(Integer pkiEzsigntemplatesignaturepaymentdetailID) {
    this.pkiEzsigntemplatesignaturepaymentdetailID = pkiEzsigntemplatesignaturepaymentdetailID;
  }

  /**
   * The unique ID of the Glaccountcontainer
   * minimum: 0
   **/
  @ApiModelProperty(required = true, value = "The unique ID of the Glaccountcontainer")
  public Integer getFkiGlaccountcontainerID() {
    return fkiGlaccountcontainerID;
  }
  public void setFkiGlaccountcontainerID(Integer fkiGlaccountcontainerID) {
    this.fkiGlaccountcontainerID = fkiGlaccountcontainerID;
  }

  /**
   * A description for the Ezsignsignaturepaymentdetail.
   **/
  @ApiModelProperty(required = true, value = "A description for the Ezsignsignaturepaymentdetail.")
  public String getTEzsigntemplatesignaturepaymentdetailDescription() {
    return tEzsigntemplatesignaturepaymentdetailDescription;
  }
  public void setTEzsigntemplatesignaturepaymentdetailDescription(String tEzsigntemplatesignaturepaymentdetailDescription) {
    this.tEzsigntemplatesignaturepaymentdetailDescription = tEzsigntemplatesignaturepaymentdetailDescription;
  }

  /**
   * The amount of the for the Ezsignsignaturepaymentdetail
   **/
  @ApiModelProperty(required = true, value = "The amount of the for the Ezsignsignaturepaymentdetail")
  public String getDEzsigntemplatesignaturepaymentdetailAmount() {
    return dEzsigntemplatesignaturepaymentdetailAmount;
  }
  public void setDEzsigntemplatesignaturepaymentdetailAmount(String dEzsigntemplatesignaturepaymentdetailAmount) {
    this.dEzsigntemplatesignaturepaymentdetailAmount = dEzsigntemplatesignaturepaymentdetailAmount;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public FieldEEzsigntemplatesignaturepaymentdetailTaxable getEEzsigntemplatesignaturepaymentdetailTaxable() {
    return eEzsigntemplatesignaturepaymentdetailTaxable;
  }
  public void setEEzsigntemplatesignaturepaymentdetailTaxable(FieldEEzsigntemplatesignaturepaymentdetailTaxable eEzsigntemplatesignaturepaymentdetailTaxable) {
    this.eEzsigntemplatesignaturepaymentdetailTaxable = eEzsigntemplatesignaturepaymentdetailTaxable;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EzsigntemplatesignaturepaymentdetailRequestCompound ezsigntemplatesignaturepaymentdetailRequestCompound = (EzsigntemplatesignaturepaymentdetailRequestCompound) o;
    return (this.pkiEzsigntemplatesignaturepaymentdetailID == null ? ezsigntemplatesignaturepaymentdetailRequestCompound.pkiEzsigntemplatesignaturepaymentdetailID == null : this.pkiEzsigntemplatesignaturepaymentdetailID.equals(ezsigntemplatesignaturepaymentdetailRequestCompound.pkiEzsigntemplatesignaturepaymentdetailID)) &&
        (this.fkiGlaccountcontainerID == null ? ezsigntemplatesignaturepaymentdetailRequestCompound.fkiGlaccountcontainerID == null : this.fkiGlaccountcontainerID.equals(ezsigntemplatesignaturepaymentdetailRequestCompound.fkiGlaccountcontainerID)) &&
        (this.tEzsigntemplatesignaturepaymentdetailDescription == null ? ezsigntemplatesignaturepaymentdetailRequestCompound.tEzsigntemplatesignaturepaymentdetailDescription == null : this.tEzsigntemplatesignaturepaymentdetailDescription.equals(ezsigntemplatesignaturepaymentdetailRequestCompound.tEzsigntemplatesignaturepaymentdetailDescription)) &&
        (this.dEzsigntemplatesignaturepaymentdetailAmount == null ? ezsigntemplatesignaturepaymentdetailRequestCompound.dEzsigntemplatesignaturepaymentdetailAmount == null : this.dEzsigntemplatesignaturepaymentdetailAmount.equals(ezsigntemplatesignaturepaymentdetailRequestCompound.dEzsigntemplatesignaturepaymentdetailAmount)) &&
        (this.eEzsigntemplatesignaturepaymentdetailTaxable == null ? ezsigntemplatesignaturepaymentdetailRequestCompound.eEzsigntemplatesignaturepaymentdetailTaxable == null : this.eEzsigntemplatesignaturepaymentdetailTaxable.equals(ezsigntemplatesignaturepaymentdetailRequestCompound.eEzsigntemplatesignaturepaymentdetailTaxable));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.pkiEzsigntemplatesignaturepaymentdetailID == null ? 0: this.pkiEzsigntemplatesignaturepaymentdetailID.hashCode());
    result = 31 * result + (this.fkiGlaccountcontainerID == null ? 0: this.fkiGlaccountcontainerID.hashCode());
    result = 31 * result + (this.tEzsigntemplatesignaturepaymentdetailDescription == null ? 0: this.tEzsigntemplatesignaturepaymentdetailDescription.hashCode());
    result = 31 * result + (this.dEzsigntemplatesignaturepaymentdetailAmount == null ? 0: this.dEzsigntemplatesignaturepaymentdetailAmount.hashCode());
    result = 31 * result + (this.eEzsigntemplatesignaturepaymentdetailTaxable == null ? 0: this.eEzsigntemplatesignaturepaymentdetailTaxable.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class EzsigntemplatesignaturepaymentdetailRequestCompound {\n");
    
    sb.append("  pkiEzsigntemplatesignaturepaymentdetailID: ").append(pkiEzsigntemplatesignaturepaymentdetailID).append("\n");
    sb.append("  fkiGlaccountcontainerID: ").append(fkiGlaccountcontainerID).append("\n");
    sb.append("  tEzsigntemplatesignaturepaymentdetailDescription: ").append(tEzsigntemplatesignaturepaymentdetailDescription).append("\n");
    sb.append("  dEzsigntemplatesignaturepaymentdetailAmount: ").append(dEzsigntemplatesignaturepaymentdetailAmount).append("\n");
    sb.append("  eEzsigntemplatesignaturepaymentdetailTaxable: ").append(eEzsigntemplatesignaturepaymentdetailTaxable).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
