/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.PermissionResponseCompound;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * A Modulesection Object
 **/
@ApiModel(description = "A Modulesection Object")
public class ModulesectionResponseCompound {
  
  @SerializedName("pkiModulesectionID")
  private Integer pkiModulesectionID = null;
  @SerializedName("fkiModuleID")
  private Integer fkiModuleID = null;
  @SerializedName("sModulesectionInternalname")
  private String sModulesectionInternalname = null;
  @SerializedName("sModulesectionNameX")
  private String sModulesectionNameX = null;
  @SerializedName("a_objPermission")
  private List<PermissionResponseCompound> aObjPermission = null;

  /**
   * The unique ID of the Modulesection
   * minimum: 0
   **/
  @ApiModelProperty(required = true, value = "The unique ID of the Modulesection")
  public Integer getPkiModulesectionID() {
    return pkiModulesectionID;
  }
  public void setPkiModulesectionID(Integer pkiModulesectionID) {
    this.pkiModulesectionID = pkiModulesectionID;
  }

  /**
   * The unique ID of the Module
   * minimum: 0
   **/
  @ApiModelProperty(required = true, value = "The unique ID of the Module")
  public Integer getFkiModuleID() {
    return fkiModuleID;
  }
  public void setFkiModuleID(Integer fkiModuleID) {
    this.fkiModuleID = fkiModuleID;
  }

  /**
   * The Internal name of the Module section.
   **/
  @ApiModelProperty(required = true, value = "The Internal name of the Module section.")
  public String getSModulesectionInternalname() {
    return sModulesectionInternalname;
  }
  public void setSModulesectionInternalname(String sModulesectionInternalname) {
    this.sModulesectionInternalname = sModulesectionInternalname;
  }

  /**
   * The Name of the Modulesection in the language of the requester
   **/
  @ApiModelProperty(required = true, value = "The Name of the Modulesection in the language of the requester")
  public String getSModulesectionNameX() {
    return sModulesectionNameX;
  }
  public void setSModulesectionNameX(String sModulesectionNameX) {
    this.sModulesectionNameX = sModulesectionNameX;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<PermissionResponseCompound> getAObjPermission() {
    return aObjPermission;
  }
  public void setAObjPermission(List<PermissionResponseCompound> aObjPermission) {
    this.aObjPermission = aObjPermission;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModulesectionResponseCompound modulesectionResponseCompound = (ModulesectionResponseCompound) o;
    return (this.pkiModulesectionID == null ? modulesectionResponseCompound.pkiModulesectionID == null : this.pkiModulesectionID.equals(modulesectionResponseCompound.pkiModulesectionID)) &&
        (this.fkiModuleID == null ? modulesectionResponseCompound.fkiModuleID == null : this.fkiModuleID.equals(modulesectionResponseCompound.fkiModuleID)) &&
        (this.sModulesectionInternalname == null ? modulesectionResponseCompound.sModulesectionInternalname == null : this.sModulesectionInternalname.equals(modulesectionResponseCompound.sModulesectionInternalname)) &&
        (this.sModulesectionNameX == null ? modulesectionResponseCompound.sModulesectionNameX == null : this.sModulesectionNameX.equals(modulesectionResponseCompound.sModulesectionNameX)) &&
        (this.aObjPermission == null ? modulesectionResponseCompound.aObjPermission == null : this.aObjPermission.equals(modulesectionResponseCompound.aObjPermission));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.pkiModulesectionID == null ? 0: this.pkiModulesectionID.hashCode());
    result = 31 * result + (this.fkiModuleID == null ? 0: this.fkiModuleID.hashCode());
    result = 31 * result + (this.sModulesectionInternalname == null ? 0: this.sModulesectionInternalname.hashCode());
    result = 31 * result + (this.sModulesectionNameX == null ? 0: this.sModulesectionNameX.hashCode());
    result = 31 * result + (this.aObjPermission == null ? 0: this.aObjPermission.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModulesectionResponseCompound {\n");
    
    sb.append("  pkiModulesectionID: ").append(pkiModulesectionID).append("\n");
    sb.append("  fkiModuleID: ").append(fkiModuleID).append("\n");
    sb.append("  sModulesectionInternalname: ").append(sModulesectionInternalname).append("\n");
    sb.append("  sModulesectionNameX: ").append(sModulesectionNameX).append("\n");
    sb.append("  aObjPermission: ").append(aObjPermission).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
