/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.18
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.ModuleResponseCompound;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ModulegroupResponseCompoundAllOf {
  
  @SerializedName("a_objModule")
  private List<ModuleResponseCompound> aObjModule = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<ModuleResponseCompound> getAObjModule() {
    return aObjModule;
  }
  public void setAObjModule(List<ModuleResponseCompound> aObjModule) {
    this.aObjModule = aObjModule;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModulegroupResponseCompoundAllOf modulegroupResponseCompoundAllOf = (ModulegroupResponseCompoundAllOf) o;
    return (this.aObjModule == null ? modulegroupResponseCompoundAllOf.aObjModule == null : this.aObjModule.equals(modulegroupResponseCompoundAllOf.aObjModule));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.aObjModule == null ? 0: this.aObjModule.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModulegroupResponseCompoundAllOf {\n");
    
    sb.append("  aObjModule: ").append(aObjModule).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
