/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.3.3
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Name of the Ezmaxpartner
 **/
@ApiModel(description = "Name of the Ezmaxpartner")
public class MultilingualEzmaxpartnerName {
  
  @SerializedName("sEzmaxpartnerName1")
  private String sEzmaxpartnerName1 = null;
  @SerializedName("sEzmaxpartnerName2")
  private String sEzmaxpartnerName2 = null;

  /**
   * The name of the Ezmaxpartner in french
   **/
  @ApiModelProperty(value = "The name of the Ezmaxpartner in french")
  public String getSEzmaxpartnerName1() {
    return sEzmaxpartnerName1;
  }
  public void setSEzmaxpartnerName1(String sEzmaxpartnerName1) {
    this.sEzmaxpartnerName1 = sEzmaxpartnerName1;
  }

  /**
   * The name of the Ezmaxpartner in english
   **/
  @ApiModelProperty(value = "The name of the Ezmaxpartner in english")
  public String getSEzmaxpartnerName2() {
    return sEzmaxpartnerName2;
  }
  public void setSEzmaxpartnerName2(String sEzmaxpartnerName2) {
    this.sEzmaxpartnerName2 = sEzmaxpartnerName2;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MultilingualEzmaxpartnerName multilingualEzmaxpartnerName = (MultilingualEzmaxpartnerName) o;
    return (this.sEzmaxpartnerName1 == null ? multilingualEzmaxpartnerName.sEzmaxpartnerName1 == null : this.sEzmaxpartnerName1.equals(multilingualEzmaxpartnerName.sEzmaxpartnerName1)) &&
        (this.sEzmaxpartnerName2 == null ? multilingualEzmaxpartnerName.sEzmaxpartnerName2 == null : this.sEzmaxpartnerName2.equals(multilingualEzmaxpartnerName.sEzmaxpartnerName2));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.sEzmaxpartnerName1 == null ? 0: this.sEzmaxpartnerName1.hashCode());
    result = 31 * result + (this.sEzmaxpartnerName2 == null ? 0: this.sEzmaxpartnerName2.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class MultilingualEzmaxpartnerName {\n");
    
    sb.append("  sEzmaxpartnerName1: ").append(sEzmaxpartnerName1).append("\n");
    sb.append("  sEzmaxpartnerName2: ").append(sEzmaxpartnerName2).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
