/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Short description of the Ezmaxpartner
 **/
@ApiModel(description = "Short description of the Ezmaxpartner")
public class MultilingualEzmaxpartnerUrl {
  
  @SerializedName("sEzmaxpartnerUrl1")
  private String sEzmaxpartnerUrl1 = null;
  @SerializedName("sEzmaxpartnerUrl2")
  private String sEzmaxpartnerUrl2 = null;

  /**
   * The url of the Ezmaxpartner website in french
   **/
  @ApiModelProperty(value = "The url of the Ezmaxpartner website in french")
  public String getSEzmaxpartnerUrl1() {
    return sEzmaxpartnerUrl1;
  }
  public void setSEzmaxpartnerUrl1(String sEzmaxpartnerUrl1) {
    this.sEzmaxpartnerUrl1 = sEzmaxpartnerUrl1;
  }

  /**
   * The url of the Ezmaxpartner website in english
   **/
  @ApiModelProperty(value = "The url of the Ezmaxpartner website in english")
  public String getSEzmaxpartnerUrl2() {
    return sEzmaxpartnerUrl2;
  }
  public void setSEzmaxpartnerUrl2(String sEzmaxpartnerUrl2) {
    this.sEzmaxpartnerUrl2 = sEzmaxpartnerUrl2;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MultilingualEzmaxpartnerUrl multilingualEzmaxpartnerUrl = (MultilingualEzmaxpartnerUrl) o;
    return (this.sEzmaxpartnerUrl1 == null ? multilingualEzmaxpartnerUrl.sEzmaxpartnerUrl1 == null : this.sEzmaxpartnerUrl1.equals(multilingualEzmaxpartnerUrl.sEzmaxpartnerUrl1)) &&
        (this.sEzmaxpartnerUrl2 == null ? multilingualEzmaxpartnerUrl.sEzmaxpartnerUrl2 == null : this.sEzmaxpartnerUrl2.equals(multilingualEzmaxpartnerUrl.sEzmaxpartnerUrl2));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.sEzmaxpartnerUrl1 == null ? 0: this.sEzmaxpartnerUrl1.hashCode());
    result = 31 * result + (this.sEzmaxpartnerUrl2 == null ? 0: this.sEzmaxpartnerUrl2.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class MultilingualEzmaxpartnerUrl {\n");
    
    sb.append("  sEzmaxpartnerUrl1: ").append(sEzmaxpartnerUrl1).append("\n");
    sb.append("  sEzmaxpartnerUrl2: ").append(sEzmaxpartnerUrl2).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
