/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.OtherincomeListElement;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Payload for GET /1/object/otherincome/getList
 **/
@ApiModel(description = "Payload for GET /1/object/otherincome/getList")
public class OtherincomeGetListV1ResponseMPayload {
  
  @SerializedName("iRowReturned")
  private Integer iRowReturned = null;
  @SerializedName("iRowFiltered")
  private Integer iRowFiltered = null;
  @SerializedName("a_objOtherincome")
  private List<OtherincomeListElement> aObjOtherincome = null;

  /**
   * The number of rows returned
   **/
  @ApiModelProperty(required = true, value = "The number of rows returned")
  public Integer getIRowReturned() {
    return iRowReturned;
  }
  public void setIRowReturned(Integer iRowReturned) {
    this.iRowReturned = iRowReturned;
  }

  /**
   * The number of rows matching your filters (if any) or the total number of rows
   **/
  @ApiModelProperty(required = true, value = "The number of rows matching your filters (if any) or the total number of rows")
  public Integer getIRowFiltered() {
    return iRowFiltered;
  }
  public void setIRowFiltered(Integer iRowFiltered) {
    this.iRowFiltered = iRowFiltered;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<OtherincomeListElement> getAObjOtherincome() {
    return aObjOtherincome;
  }
  public void setAObjOtherincome(List<OtherincomeListElement> aObjOtherincome) {
    this.aObjOtherincome = aObjOtherincome;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OtherincomeGetListV1ResponseMPayload otherincomeGetListV1ResponseMPayload = (OtherincomeGetListV1ResponseMPayload) o;
    return (this.iRowReturned == null ? otherincomeGetListV1ResponseMPayload.iRowReturned == null : this.iRowReturned.equals(otherincomeGetListV1ResponseMPayload.iRowReturned)) &&
        (this.iRowFiltered == null ? otherincomeGetListV1ResponseMPayload.iRowFiltered == null : this.iRowFiltered.equals(otherincomeGetListV1ResponseMPayload.iRowFiltered)) &&
        (this.aObjOtherincome == null ? otherincomeGetListV1ResponseMPayload.aObjOtherincome == null : this.aObjOtherincome.equals(otherincomeGetListV1ResponseMPayload.aObjOtherincome));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.iRowReturned == null ? 0: this.iRowReturned.hashCode());
    result = 31 * result + (this.iRowFiltered == null ? 0: this.iRowFiltered.hashCode());
    result = 31 * result + (this.aObjOtherincome == null ? 0: this.aObjOtherincome.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OtherincomeGetListV1ResponseMPayload {\n");
    
    sb.append("  iRowReturned: ").append(iRowReturned).append("\n");
    sb.append("  iRowFiltered: ").append(iRowFiltered).append("\n");
    sb.append("  aObjOtherincome: ").append(aObjOtherincome).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
