/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.17
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.PaymenttermListElement;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class PaymenttermGetListV1ResponseMPayloadAllOf {
  
  @SerializedName("a_objPaymentterm")
  private List<PaymenttermListElement> aObjPaymentterm = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<PaymenttermListElement> getAObjPaymentterm() {
    return aObjPaymentterm;
  }
  public void setAObjPaymentterm(List<PaymenttermListElement> aObjPaymentterm) {
    this.aObjPaymentterm = aObjPaymentterm;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymenttermGetListV1ResponseMPayloadAllOf paymenttermGetListV1ResponseMPayloadAllOf = (PaymenttermGetListV1ResponseMPayloadAllOf) o;
    return (this.aObjPaymentterm == null ? paymenttermGetListV1ResponseMPayloadAllOf.aObjPaymentterm == null : this.aObjPaymentterm.equals(paymenttermGetListV1ResponseMPayloadAllOf.aObjPaymentterm));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.aObjPaymentterm == null ? 0: this.aObjPaymentterm.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymenttermGetListV1ResponseMPayloadAllOf {\n");
    
    sb.append("  aObjPaymentterm: ").append(aObjPaymentterm).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
