/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Payload for POST /1/object/signature
 **/
@ApiModel(description = "Payload for POST /1/object/signature")
public class SignatureCreateObjectV1ResponseMPayload {
  
  @SerializedName("a_pkiSignatureID")
  private List<Integer> aPkiSignatureID = null;

  /**
   * An array of unique IDs representing the object that were requested to be created.  They are returned in the same order as the array containing the objects to be created that was sent in the request.
   **/
  @ApiModelProperty(required = true, value = "An array of unique IDs representing the object that were requested to be created.  They are returned in the same order as the array containing the objects to be created that was sent in the request.")
  public List<Integer> getAPkiSignatureID() {
    return aPkiSignatureID;
  }
  public void setAPkiSignatureID(List<Integer> aPkiSignatureID) {
    this.aPkiSignatureID = aPkiSignatureID;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignatureCreateObjectV1ResponseMPayload signatureCreateObjectV1ResponseMPayload = (SignatureCreateObjectV1ResponseMPayload) o;
    return (this.aPkiSignatureID == null ? signatureCreateObjectV1ResponseMPayload.aPkiSignatureID == null : this.aPkiSignatureID.equals(signatureCreateObjectV1ResponseMPayload.aPkiSignatureID));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.aPkiSignatureID == null ? 0: this.aPkiSignatureID.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureCreateObjectV1ResponseMPayload {\n");
    
    sb.append("  aPkiSignatureID: ").append(aPkiSignatureID).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
