/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Payload for POST /1/object/supply
 **/
@ApiModel(description = "Payload for POST /1/object/supply")
public class SupplyCreateObjectV1ResponseMPayload {
  
  @SerializedName("a_pkiSupplyID")
  private List<Integer> aPkiSupplyID = null;

  /**
   * An array of unique IDs representing the object that were requested to be created.  They are returned in the same order as the array containing the objects to be created that was sent in the request.
   **/
  @ApiModelProperty(required = true, value = "An array of unique IDs representing the object that were requested to be created.  They are returned in the same order as the array containing the objects to be created that was sent in the request.")
  public List<Integer> getAPkiSupplyID() {
    return aPkiSupplyID;
  }
  public void setAPkiSupplyID(List<Integer> aPkiSupplyID) {
    this.aPkiSupplyID = aPkiSupplyID;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SupplyCreateObjectV1ResponseMPayload supplyCreateObjectV1ResponseMPayload = (SupplyCreateObjectV1ResponseMPayload) o;
    return (this.aPkiSupplyID == null ? supplyCreateObjectV1ResponseMPayload.aPkiSupplyID == null : this.aPkiSupplyID.equals(supplyCreateObjectV1ResponseMPayload.aPkiSupplyID));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.aPkiSupplyID == null ? 0: this.aPkiSupplyID.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SupplyCreateObjectV1ResponseMPayload {\n");
    
    sb.append("  aPkiSupplyID: ").append(aPkiSupplyID).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
