/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.3.2
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * A Systemconfigurationtype AutocompleteElement Response
 **/
@ApiModel(description = "A Systemconfigurationtype AutocompleteElement Response")
public class SystemconfigurationtypeAutocompleteElementResponse {
  
  @SerializedName("pkiSystemconfigurationtypeID")
  private Integer pkiSystemconfigurationtypeID = null;
  @SerializedName("sSystemconfigurationtypeDescriptionX")
  private String sSystemconfigurationtypeDescriptionX = null;
  @SerializedName("bSystemconfigurationtypeIsactive")
  private Boolean bSystemconfigurationtypeIsactive = null;

  /**
   * The unique ID of the Systemconfigurationtype
   * minimum: 1
   **/
  @ApiModelProperty(required = true, value = "The unique ID of the Systemconfigurationtype")
  public Integer getPkiSystemconfigurationtypeID() {
    return pkiSystemconfigurationtypeID;
  }
  public void setPkiSystemconfigurationtypeID(Integer pkiSystemconfigurationtypeID) {
    this.pkiSystemconfigurationtypeID = pkiSystemconfigurationtypeID;
  }

  /**
   * The description of the Systemconfigurationtype in the language of the requester
   **/
  @ApiModelProperty(required = true, value = "The description of the Systemconfigurationtype in the language of the requester")
  public String getSSystemconfigurationtypeDescriptionX() {
    return sSystemconfigurationtypeDescriptionX;
  }
  public void setSSystemconfigurationtypeDescriptionX(String sSystemconfigurationtypeDescriptionX) {
    this.sSystemconfigurationtypeDescriptionX = sSystemconfigurationtypeDescriptionX;
  }

  /**
   * Whether Systemconfigurationtype is active or not
   **/
  @ApiModelProperty(required = true, value = "Whether Systemconfigurationtype is active or not")
  public Boolean getBSystemconfigurationtypeIsactive() {
    return bSystemconfigurationtypeIsactive;
  }
  public void setBSystemconfigurationtypeIsactive(Boolean bSystemconfigurationtypeIsactive) {
    this.bSystemconfigurationtypeIsactive = bSystemconfigurationtypeIsactive;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SystemconfigurationtypeAutocompleteElementResponse systemconfigurationtypeAutocompleteElementResponse = (SystemconfigurationtypeAutocompleteElementResponse) o;
    return (this.pkiSystemconfigurationtypeID == null ? systemconfigurationtypeAutocompleteElementResponse.pkiSystemconfigurationtypeID == null : this.pkiSystemconfigurationtypeID.equals(systemconfigurationtypeAutocompleteElementResponse.pkiSystemconfigurationtypeID)) &&
        (this.sSystemconfigurationtypeDescriptionX == null ? systemconfigurationtypeAutocompleteElementResponse.sSystemconfigurationtypeDescriptionX == null : this.sSystemconfigurationtypeDescriptionX.equals(systemconfigurationtypeAutocompleteElementResponse.sSystemconfigurationtypeDescriptionX)) &&
        (this.bSystemconfigurationtypeIsactive == null ? systemconfigurationtypeAutocompleteElementResponse.bSystemconfigurationtypeIsactive == null : this.bSystemconfigurationtypeIsactive.equals(systemconfigurationtypeAutocompleteElementResponse.bSystemconfigurationtypeIsactive));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.pkiSystemconfigurationtypeID == null ? 0: this.pkiSystemconfigurationtypeID.hashCode());
    result = 31 * result + (this.sSystemconfigurationtypeDescriptionX == null ? 0: this.sSystemconfigurationtypeDescriptionX.hashCode());
    result = 31 * result + (this.bSystemconfigurationtypeIsactive == null ? 0: this.bSystemconfigurationtypeIsactive.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SystemconfigurationtypeAutocompleteElementResponse {\n");
    
    sb.append("  pkiSystemconfigurationtypeID: ").append(pkiSystemconfigurationtypeID).append("\n");
    sb.append("  sSystemconfigurationtypeDescriptionX: ").append(sSystemconfigurationtypeDescriptionX).append("\n");
    sb.append("  bSystemconfigurationtypeIsactive: ").append(bSystemconfigurationtypeIsactive).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
