/**
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Payload for POST /1/object/usergroupdelegation
 **/
@ApiModel(description = "Payload for POST /1/object/usergroupdelegation")
public class UsergroupdelegationCreateObjectV1ResponseMPayload {
  
  @SerializedName("a_pkiUsergroupdelegationID")
  private List<Integer> aPkiUsergroupdelegationID = null;

  /**
   * An array of unique IDs representing the object that were requested to be created.  They are returned in the same order as the array containing the objects to be created that was sent in the request.
   **/
  @ApiModelProperty(required = true, value = "An array of unique IDs representing the object that were requested to be created.  They are returned in the same order as the array containing the objects to be created that was sent in the request.")
  public List<Integer> getAPkiUsergroupdelegationID() {
    return aPkiUsergroupdelegationID;
  }
  public void setAPkiUsergroupdelegationID(List<Integer> aPkiUsergroupdelegationID) {
    this.aPkiUsergroupdelegationID = aPkiUsergroupdelegationID;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsergroupdelegationCreateObjectV1ResponseMPayload usergroupdelegationCreateObjectV1ResponseMPayload = (UsergroupdelegationCreateObjectV1ResponseMPayload) o;
    return (this.aPkiUsergroupdelegationID == null ? usergroupdelegationCreateObjectV1ResponseMPayload.aPkiUsergroupdelegationID == null : this.aPkiUsergroupdelegationID.equals(usergroupdelegationCreateObjectV1ResponseMPayload.aPkiUsergroupdelegationID));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.aPkiUsergroupdelegationID == null ? 0: this.aPkiUsergroupdelegationID.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsergroupdelegationCreateObjectV1ResponseMPayload {\n");
    
    sb.append("  aPkiUsergroupdelegationID: ").append(aPkiUsergroupdelegationID).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
